services:
    # Repositories
    AppBundle\Repository\AbstractRepository:
        abstract: true
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']

    AppBundle\Entity\Repository\EventRepository:
        parent: AppBundle\Repository\AbstractRepository
        arguments:
            - AppBundle\Entity\Event